services:
  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - "5173"
    networks:
      - food-network

  admin:
    build: ./admin
    container_name: admin
    expose:
      - "5174"
    networks:
      - food-network

  backend:
    build: ./backend
    container_name: backend
    env_file:
      - ./backend/.env
    expose:
      - "5000"
    networks:
      - food-network

  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - frontend
      - admin
      - backend
    ports:
      - "80:80"
    networks:
      - food-network

networks:
  food-network:
    driver: bridge
